# Generated by Django 4.1.2 on 2022-10-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodes',
            name='social_logo',
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='full_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='social_other_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='social_other_link_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='website',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
