# Generated by Django 4.1.1 on 2022-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0002_qrcodes_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='firstSet',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='gradient',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='isDynamic',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='no_logo_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='transparent_code',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
