# Generated by Django 4.1.2 on 2022-10-26 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0002_alter_qrcodes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 26, 13, 31, 6, 905907)),
        ),
    ]
