# Generated by Django 4.1.2 on 2022-10-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0003_alter_qrcodes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
