# Generated by Django 4.1.1 on 2022-10-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0003_alter_qrcodes_firstset_alter_qrcodes_gradient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='isDynamic',
            field=models.BooleanField(default=True),
        ),
    ]
