# Generated by Django 4.1.1 on 2022-10-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0004_alter_qrcodes_isdynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
