# Generated by Django 4.0.2 on 2022-10-07 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0006_archivedqrcodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedQrcodes',
        ),
    ]
