# Generated by Django 4.0.2 on 2022-10-07 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0007_delete_archivedqrcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 7, 18, 4, 54, 558229)),
        ),
    ]
