# Generated by Django 4.0.2 on 2022-10-09 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0008_qrcodes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='qrData',
            field=models.CharField(default='', max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 22, 49, 18, 894469)),
        ),
    ]
