# Generated by Django 4.0.2 on 2022-10-09 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0009_qrcodes_qrdata_alter_qrcodes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='uuid',
            field=models.CharField(default='man', max_length=1000),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 45, 26, 668943)),
        ),
    ]
