# Generated by Django 4.0.2 on 2022-10-09 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0010_qrcodes_uuid_alter_qrcodes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='qrCodeimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 1, 11, 57, 432928)),
        ),
    ]
