# Generated by Django 4.0.2 on 2022-10-09 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0012_alter_qrcodes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 1, 48, 42, 890505)),
        ),
    ]
