# Generated by Django 4.0.2 on 2022-10-13 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0013_alter_qrcodes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='qrname',
            field=models.CharField(default='Untitled', max_length=250),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 13, 49, 57, 490768)),
        ),
    ]
