# Generated by Django 4.0.2 on 2022-10-15 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0014_qrcodes_qrname_alter_qrcodes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodes',
            name='staticsss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 15, 11, 58, 38, 956663)),
        ),
    ]
