# Generated by Django 4.1.2 on 2022-10-25 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRLabs', '0015_qrcodes_staticsss_alter_qrcodes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 25, 12, 18, 45, 722400)),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
